Fix native extension building on XCode 14
XCode 14 on macOS compiles Ruby 2.7.5 without the linker flag
`-Wl,-undefined,dynamic_lookup`, as reported
in https://bugs.ruby-lang.org/issues/19005. As a result, the build
step fails:

```
linking shared-object oj/introspect/introspect_ext.bundle
Undefined symbols for architecture arm64:
  "_oj_init_usual", referenced from:
      _rb_new_introspect_parser in introspect.o
  "_oj_parser_new", referenced from:
      _rb_new_introspect_parser in introspect.o
  "_oj_parser_set_option", referenced from:
      _rb_new_introspect_parser in introspect.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:262: introspect_ext.bundle] Error 1
```

This commit ignores the symbols needed from Oj so that compilation
will not fail if these are not available.

In addition, this commit ensures `_ruby_abi_version` is exported for
Ruby 3.2 to support https://github.com/ruby/ruby/pull/5474.